/********
 * This file is part of Ext.NET.
 *     
 * Ext.NET is free software: you can redistribute it and/or modify
 * it under the terms of the GNU AFFERO GENERAL PUBLIC LICENSE as 
 * published by the Free Software Foundation, either version 3 of the 
 * License, or (at your option) any later version.
 * 
 * Ext.NET is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU AFFERO GENERAL PUBLIC LICENSE for more details.
 * 
 * You should have received a copy of the GNU AFFERO GENERAL PUBLIC LICENSE
 * along with Ext.NET.  If not, see <http://www.gnu.org/licenses/>.
 *
 *
 * @version   : 1.2.0 - Ext.NET Pro License
 * @author    : Ext.NET, Inc. http://www.ext.net/
 * @date      : 2011-09-12
 * @copyright : Copyright (c) 2006-2011, Ext.NET, Inc. (http://www.ext.net/). All rights reserved.
 * @license   : GNU AFFERO GENERAL PUBLIC LICENSE (AGPL) 3.0. 
 *              See license.txt and http://www.ext.net/license/.
 *              See AGPL License at http://www.gnu.org/licenses/agpl-3.0.txt
 ********/

using System.ComponentModel;

namespace Ext.Net
{
	/// <summary>
	/// 
	/// </summary>
	[Description("")]
    public enum IDMode
    {
        /// <summary>
        /// [Default] Inherits the IDMode for the Parent. This is the default functionality of all Ext.Net Components.
        /// </summary>
        Inherit,
        
        /// <summary>
        /// Legacy functionality for generating CliendID's. No change from default ASP.NET functionality.
        /// </summary>
        Legacy,
        
        /// <summary>
        /// Render the "id" property in the client as exactly the value set. Developer must manually ensure client-side ID uniqueness.
        /// </summary>
        Static,
        
        /// <summary>
        /// Do not render the "id" property in the client. 
        /// </summary>
        Ignore,
        
        /// <summary>
        /// Only render the "id" property if the .ID is explicitly set, otherwise renders as the ClientID if autogenerated by the ASP.NET runtime.
        /// </summary>
        Explicit,

        /// <summary>
        /// Only render the ClientID property if the .ID is explicitly set.
        /// </summary>
        Client,

        /// <summary>
        /// The ClientID value is generated by concatenating the ID value of the parent naming container with the ID value of the control. Each segment is separated by an underscore character (_).
        /// </summary>
        Predictable,

        /// <summary>
        /// The ClientID value is generated by concatenating the ID value of the parent Ext.NET component of the parent naming container with the ID value of the control. Each segment is separated by an underscore character (_).
        /// </summary>
        Parent
    }
}